server:
  port: 17001

eureka:
  client:
    service-url:
      defaultZone: http://admin:14780118635@118.24.38.46:10001/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 118.24.38.46

spring:
  application:
    name: ssaw-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IsSenHu/ssaw-config.git
          username: 1178515826@qq.com
          password: 521428Slyt
          default-label: master
          search-paths: ssaw-demo,ssaw-consumer-demo,user-resource
        health:                                           #监控检查配置
          repositories:
            check:
              name: ssaw-demo,ssaw-consumer-demo
              label: master,dev-husen
              profiles: default,test,dev,prod
        overrides:                                        #属性覆盖，提供默认配置
          name: HuSen
    bus:                                                  #bus
      enabled: true                                       #开启消息总线信息的监听和记录
      trace:
        enabled: true                                     #开启消息总线跟踪信息的监听和记录
      destination: configBus                              #指定交换机名称

  security:                                               #用户密码认证
    user:
      name: admin
      password: 521428Slyt

  rabbitmq:                                               #amqp
    host: localhost
    port: 5672
    username: husen
    password: 521428
    virtual-host: /

  thymeleaf:                                              #thymeleaf配置
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh                              #消息总线刷新的位置


